export interface Forecast {
    cod: string,
    message:number,
    cnt:number,
    list:[
        {
            dt:number,
            sunrise:number,
            sunset:number,
            temp:{
                day:number,
                min:number,
                max:number,
                night:number,
                eve:number,
                morn:number
            },
            feels_like:{
                day:number,
                night:number,
                eve:number,
                morn:number
            },
            pressure:number,
            humidity:number,
            weather:[
                {
                    id:number,
                    main:string,
                    description:string,
                    icon:string
                }
            ],
            speed:number,
            deg:number,
            gust:number,
            clouds:number,
            pop:number,
            rain:number
        }
      ],
      city:{
        id:1273294,
        name:"Delhi",
        coord:{
            lat:28.6667,
            lon:77.2167
        },
        country:"IN",
        population:10927986,
        timezone:19800,
        sunrise:1659226299,
        sunset:1659274995
    }
}